### ISSUE TITLE
Supports redis as service db (cloudi_service_db_redis)

### ISSUE THREAD

**Issue by hey-jude** [CloudI/CloudI#162]
Do you have a plan?

**Comment by okeuday** [comment]
I have not attempted to create cloudi_service_db_redis yet, but it should be relatively straight-forward if you wanted to try.  There are many examples of other database services in CloudI and cloudi_service_db_pgsql or cloudi_service_db_mysql provide good examples.  The recommended Erlang driver for redis is https://github.com/wooga/eredis (based on http://redis.io/clients), so that should be the best Erlang driver to use in cloudi_service_db_redis.  Did you want to add it?

**Comment by hey-jude** [comment]
Thank you for your suggestion, but I don't have experience of coding erlang. I just beginned learning elixir.

Anyway, supporting redis is so important thing as I think.

**Comment by okeuday** [comment]
Ok, I will look at adding this to the next release.

**Comment by hey-jude** [comment]
:+1:

**Comment by okeuday** [comment]
After thinking about this for a decent period of time, it seems best to not have a redis service within CloudI and instead just have developers that use CloudI utilize any redis client within a CloudI service.  For redis usage, there isn't a clear benefit to providing a redis CloudI service (there is a clear benefit for SQL databases, due to scalability challenges there, but redis is attempting to handling scalability challenges itself).  So, closing this issue now because the redis service should be unnecessary and probably undesirable (it is better to manage faults related to the database usage in the same service).
