### ISSUE TITLE
How to use internal service?

### ISSUE THREAD

**Issue by RichardFreeman** [CloudI/CloudI#169]
eg:

cloudi console

after this, how to create a couchdb database?

**Comment by okeuday** [comment]
First, instead of using `cloudi console` you probably want to do `cloudi start` and then `cloudi attach` just because quitting the console brings down the CloudI node, while attaching to then running node can safely detach.

There is an older (from 2009) Erlang driver for CouchDB integrated into a CloudI service at https://github.com/CloudI/CloudI/blob/develop/src/lib/cloudi_service_db_couchdb/src/cloudi_service_db_couchdb.erl which you can start to interact with CouchDB using CloudI service requests.  There already is an issue filed to update the driver https://github.com/CloudI/CloudI/issues/141 and the cloudi_service_db_couchdb service doesn't have tests yet, so your mileage on that path may vary.

The other option is to write usage of CouchDB in a programming language CloudI supports and make that source code a CloudI service.  It depends on your use case what path you would take.  It is easier to dynamically scale and have fault-tolerance with a CloudI service handling the database connections, however, there is more development flexibility when you can use any CouchDB driver in any supported programming language.

I am not sure when cloudi_service_db_couchdb will get improved.  The next release (1.5.1) is going to focus on documentation and a UI, so I am not sure if it will be possible to improve cloudi_service_db_couchdb for 1.5.1.

**Comment by RichardFreeman** [comment]
okay, I see,  I just want to test the database service by using the CloudI module and the associated Erlang VM shell, If not CouchDB, or PgSQL and so on.

**Comment by okeuday** [comment]
@RichardFreeman All the provided internal CloudI services are named with a `cloudi_service_` prefix and all the database connection internal CloudI services have a `cloudi_service_db_` prefix, which should make them easier to find.  The `cloudi_service_db_pgsql` internal CloudI service provides integration with 3 different Erlang PostgreSQL drivers with the `driver` configuration argument.  The various configuration arguments are shown in the source code of each internal CloudI service as shown at https://github.com/CloudI/CloudI/blob/develop/src/lib/cloudi_service_db_pgsql/src/cloudi_service_db_pgsql.erl#L71-L86 .  The `cloudi_service_db_mysql` internal CloudI service also is provided and both the `cloudi_service_db_pgsql` and `cloudi_service_db_mysql` services use similar tests.

**Comment by okeuday** [comment]
Reopen if you still have other questions.
