### ISSUE TITLE
init terminating in do_boot

### ISSUE THREAD

**Issue by bayuemu** [CloudI/CloudI#201]
=====
===== LOGGING STARTED Fri Jan 13 03:31:26 GMT 2017
=====
Exec: /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi/erts-8.1/bin/erlexec -boot /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi/releases/1/cloudi -mode embedded -config /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi/etc/app.config -args_file /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi/etc/vm.args -- console ''
Root: /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi
{"init terminating in do_boot",{load_failed,['Elixir.Elixir.CloudILogger']}}

init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done

=====
===== LOGGING STARTED Fri Jan 13 03:41:17 GMT 2017
=====
Exec: /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi/erts-8.1/bin/erlexec -boot /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi/releases/1/cloudi -mode embedded -config /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi/etc/app.config -args_file /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi/etc/vm.args -- console ''
Root: /home/lyf/src/CloudI-1.6.0/install_local/lib/cloudi
{"init terminating in do_boot",{load_failed,['Elixir.Elixir.CloudILogger']}}

init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done

-----cloudi 1.6.0

**Comment by okeuday** [comment]
@bayuemu It looks like you are using this CloudI as a rebar2 dep, and this problem should be being caused by old rebar2 source code which is attempting to handle Erlang/OTP packages, though that support may have never worked and Erlang/OTP packages no longer exist.  The change I added to the CloudI rebar2 is at https://github.com/CloudI/CloudI/commit/5abcbe8f5fcaa0b98c6ba987b8008a3da52af487#diff-d9a88b4284b1eaba08f7c4f6d7ad909e .  If you use the rebar2 version that is provided with CloudI, things should work fine.  However, I am not sure about being able to support this rebar2 dep usage in the future, due to rebar3 having removed "raw" deps.  I understand that this problem is related to the [hello_world3](https://github.com/CloudI/CloudI/tree/develop/examples/hello_world3) example, though that must change due to rebar3 not attempting to be backwards compatible with rebar2.

**Comment by okeuday** [comment]
@bayuemu Instead of attempting to use a rebar2 "raw" dep, it is better to pull CloudI into a release, as shown in the [hello_world2](https://github.com/CloudI/CloudI/tree/develop/examples/hello_world2) or [hello_world4](https://github.com/CloudI/CloudI/tree/develop/examples/hello_world4) examples.  The  [hello_world3](https://github.com/CloudI/CloudI/tree/develop/examples/hello_world3) rebar2 "raw" dep route requires continuous compilation to manage the deps with rebar2, not due to CloudI, but just due to rebar2 dependency issues.

So, it should be best to remove the `hello_world2` example when converting the CloudI repo to use rebar3.  Will keep this issue open and dependent upon rebar3 use (https://github.com/CloudI/CloudI/issues/183).

**Comment by bayuemu** [comment]
thank you !
