### ISSUE TITLE
python cloudi.API.subscribe

### ISSUE THREAD

**Issue by bmccary** [CloudI/CloudI#214]
In [CloudI's python API module](https://github.com/CloudI/CloudI/blob/master/src/api/python/cloudi.py), in API class's function `subscribe` on [line 105](https://github.com/CloudI/CloudI/blob/6d51d1a0415e651006ca27689c708d1043875c1c/src/api/python/cloudi.py#L105), there is a check to make sure the function has exactly 10 positional arguments. The comment on this conditional is: `# self + arguments, so a non-static method`, which I take to mean 1 class instance object + the 9 parameters from CloudI. Such a method is called [bound method](https://docs.python.org/2/library/inspect.html). The source code to python's [types module](https://github.com/python/cpython/blob/2.7/Lib/types.py) gives the full story (be sure to compare to 3.7).

I came across these lines of code when I tried to make the MWE below, which uses a function instead of a class method, and so always generated an error on line 105. Looking through the source of the module, I don't see anywhere the API actually requires/uses the fact that the callback is a bound method, other than the conditional mentioned above. Is it possible/reasonable to change the conditional to something like:

```python
    def subscribe(self, pattern, Function):
        isf = inspect.isfunction(Function)
        ism = inspect.ismethod(Function)
        if isf or ism:
            expected_args_len = 9 # CloudI's 9 args
            if ism:
                expected_args_len += 1 # and one more for self
            args, varargs, varkw, defaults = inspect.getargspec(Function)
            if len(args) != expected_args_len:
                raise invalid_input_exception()
        else:
            raise invalid_input_exception()
        # rest of function omitted ...
```

MWE without a class (derived from the MWE in the CloudI FAQ):

```python
import sys 
import traceback
from cloudi import API, terminate_exception
import os

def hello_world(command, name, pattern, request_info, request, timeout, priority, trans_id, pid):
    return bytes('Hello from PID: {pid}'.format(pid=os.getpid()), 'utf-8')

if __name__ == '__main__':
    assert API.thread_count() == 1
    api = API(0)
    try:
        # The next line fails the test on line 105 because 
        # hello_world has 9 arguments, not 10
        api.subscribe("hello_world/get", hello_world)
        api.poll()
    except terminate_exception:
        pass
    except:
        traceback.print_exc(file=sys.stderr)
```

**Comment by okeuday** [comment]
@bmccary Yes, that would be a good change to add.  The function used for a subscribe is meant to be flexible and avoiding a member function can help indicate you are avoiding side-effects (i.e., not mutating object state when handling a service request).  The C++ CloudI API has similar flexibility and it would be nice to have it in the Python CloudI API.

However, the Python/C CloudI API (the cloudi_c) module appears to lack checking on the function arguments, so that may currently work due to a lack of checking.  It would be best to add the same function argument checking to the cloudi_c module and that change is easiest in Python source code (subscribe is not a latency sensitive function due to it being called infrequently, so adding some extra checking isn't a problem).

Feel free to submit a pull request.  In the pull request, it would be good to exercise the non-member function use in the examples/integration-tests (they typically use the same Python source code with both the cloudi module and the cloudi_c module).  A good one to change is https://github.com/CloudI/CloudI/blob/develop/src/tests/msg_size/msg_size.py (to be similar to how the cxx msg_size source code is using the C CloudI API) to use a static method.

**Comment by okeuday** [comment]
@bmccary After thinking about this more, it bothers me a little due to the callback function lacking the CloudI API object when not having the `self` argument.  That means that the function is generally unable to do much unless it relies on global state, which is best to avoid for concurrency/threading, maintainability, etc..  The C++ CloudI API is able to provide the CloudI API as a separate function argument though that doesn't fit well into the Python CloudI API due to the `self` argument needing to be the default and most typical use for the `subscribe` function argument.

It would be possible to use the check that determines whether it is a member function to choose between whether a `self` object or the CloudI API object is used.  I think that approach may be the best, though it may confuse users by the fact the arity stays the same.  With proper argument naming confusion could be avoided.

**Comment by okeuday** [comment]
I have added the changes described here to allow a non-member function to be used with the Python CloudI API or the Python/C CloudI API.  The `msg_size` integration test (https://github.com/CloudI/CloudI/blob/beed2dfafa68e5f4edcdd915f604693f4e85c01e/src/tests/msg_size/msg_size.py) was updated to use a non-member function.  Thanks for filing this issue!
