### ISSUE TITLE
erlzmq2 build can fail silently

### ISSUE THREAD

**Issue by okeuday** [CloudI/CloudI#38]
Currently, rebar isn't providing success/fail from an erlzmq2 build... a proper zeromq install is assumed to provide a working erlzmq2 build.  Need to change the configure script to fail if erlzmq2 compilation fails.  This may be easiest with autoconf/automake inserting erlzmq2 to be built with the other Erlang dependencies (currently it is built separately).

**Comment by okeuday** [comment]
Revisit when doing https://github.com/CloudI/CloudI/issues/183

**Comment by bobgus** [comment]
I'm trying to build cloudi with zeromq on both OS X (home-brew) and Fedora 25. I get similar errors - cannot file the libzmq.a library. On OS X, the failure is more silent than on Fedora. Sometimes the OS X integration tests run longer..

A few questions:
1) Do I really want/need the zeromq features? (I would like to create a network layer connecting systems on my local lan (including the mac air and the Fedora system)
2) Clicking around, I discovered a pure Erlang implementation of zeromq.(https://github.com/zeromq/ezmq). Since Erlang is already a necessary part of Cloudi, would this implementation of zeromq be 'better' for Cloudi?
3) This problem seems to be on a low priority track. Is this because it is generally not needed, or is it left as more of an 'exercise for the enthusiast'?

**Comment by okeuday** [comment]
@bobgus You don't really need zeromq, it is mainly an example of integrating CloudI service requests with a different messaging bus.  The main reason to avoid zeromq, is that its license is LGPL/GPL, so it prevents commercial reuse that uses private modifications (and gets less testing due to that).  That is part of the reason why I haven't considered this issue a high priority, along with the build system and cross-platform details in the erlzmq2 compilation (an Erlang NIF).

Instead, it is better to focus on using CloudI service requests.  With distributed Erlang messaging, the nodes can communicate on a LAN, and CloudI provides the automatic node discovery which can make this simpler.  The communication is not meant to be secure, but the connectivity is fault-tolerant, so node-splits are handled.  It is possible to configure distributed Erlang with SSL if necessary, but I think it is better to have a private LAN for lower latency communication (i.e., an air-gap network for security).

**Comment by bobgus** [comment]
Ok, sounds good. I will remove the "--with_zeromq=yes" from my build script.

 I will be needing SSL eventually. Will this requirement make zeromq more desirable for off-LAN messaging?

**Comment by okeuday** [comment]
@bobgus Not really.  ZeroMQ has its own encryption in v4, but it is unclear how much it gets used, since ZeroMQ's popularity seemed to decrease around that point, as they created their own approach to crypto (that attempts to deal with reconnections, if I remember properly, http://zeromq.org/topics:encryption).  For WAN secure messaging it is more typical to use HTTPS which you can do through cloudi_service_http_cowboy when relying on the Erlang/OTP ssl source code, if you want the incoming HTTPS requests to automatically become CloudI service requests.

**Comment by bobgus** [comment]
Ok, super. Thanks much. I will proceed with plain vanilla.

**Comment by okeuday** [comment]
Closing, to handle this as the issue https://github.com/CloudI/CloudI/issues/211
